# very simple travis file to test how things are going
env:
    - PYTHONPATH=`pwd`
language: python 
python:
    - "3.6"
install:
    - pip install pipenv
    - pipenv sync
before_script:
    - gcc -o tools/sph2pipe/sph2pipe tools/sph2pipe/*.c -lm
script: pytest tests/sig
